// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDobMNjeHgWnYefeAQvw-2tXRlUAdihutU',
    appId: '1:593274810667:web:b4752a8e96c0040de4956e',
    messagingSenderId: '593274810667',
    projectId: 'practicaltest-3e9d0',
    authDomain: 'practicaltest-3e9d0.firebaseapp.com',
    databaseURL: 'https://practicaltest-3e9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practicaltest-3e9d0.appspot.com',
    measurementId: 'G-F9LMEHJ7SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQiu_QfvG8-FQ_mJfleveuXsz8EifsKAk',
    appId: '1:593274810667:android:ba9fc6fff5705fbde4956e',
    messagingSenderId: '593274810667',
    projectId: 'practicaltest-3e9d0',
    databaseURL: 'https://practicaltest-3e9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practicaltest-3e9d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtV-Ctgq8jnl_BKTfxvOW8iInkrRPHkPs',
    appId: '1:593274810667:ios:5944304933625b7be4956e',
    messagingSenderId: '593274810667',
    projectId: 'practicaltest-3e9d0',
    databaseURL: 'https://practicaltest-3e9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practicaltest-3e9d0.appspot.com',
    iosBundleId: 'com.example.practicaltest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtV-Ctgq8jnl_BKTfxvOW8iInkrRPHkPs',
    appId: '1:593274810667:ios:5944304933625b7be4956e',
    messagingSenderId: '593274810667',
    projectId: 'practicaltest-3e9d0',
    databaseURL: 'https://practicaltest-3e9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practicaltest-3e9d0.appspot.com',
    iosBundleId: 'com.example.practicaltest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDobMNjeHgWnYefeAQvw-2tXRlUAdihutU',
    appId: '1:593274810667:web:1717e5f34245f686e4956e',
    messagingSenderId: '593274810667',
    projectId: 'practicaltest-3e9d0',
    authDomain: 'practicaltest-3e9d0.firebaseapp.com',
    databaseURL: 'https://practicaltest-3e9d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practicaltest-3e9d0.appspot.com',
    measurementId: 'G-GBFF6KJXJM',
  );
}
